server:
  port: 9094

spring:
  application:
    name: activity-service

# Comment out Config Server import until your config server is running
  config:
    import: optional:configserver:http://localhost:8888

